import { Sanchez, Miniver, Poppins, Nunito, Roboto } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Navbar from '@/components/Navbar';


// Import the fonts and configure them
const sanchez = Sanchez({
  weight: ['400'], // You can add more weights if needed
  subsets: ['latin'],
  variable: '--font-sanchez',
});

const miniver = Miniver({
  weight: ['400'], // Miniver typically has one weight
  subsets: ['latin'],
  variable: '--font-miniver',
});

const poppins = Poppins({
  weight: ['400', '600', '700'], // Add desired weights
  subsets: ['latin'],
  variable: '--font-poppins',
});

const nunito = Nunito({
  weight: ['400', '600', '700'], // Add desired weights
  subsets: ['latin'],
  variable: '--font-nunito',
});

const roboto = Roboto({
  weight: ['400', '700'], // Add desired weights
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${sanchez.variable} ${miniver.variable} ${poppins.variable} ${nunito.variable} ${roboto.variable} antialiased`}
      >
        {/* <Navbar /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
